# versions:
#   pipx_installer: "1.6.0"   # renovate: datasource=github-releases depName=pypa/pipx

brew_kegs:
  - robusta-dev/homebrew-krr

brew_packages:
  - gcc
  - starship
  - age
  - atuin
  - bat
  - cue
  - eza
  - fluxcd/tap/flux
  - gh
  - go-task
  - hadolint
  - helm
  - hugo
  - jump
  - k9s
  - kubernetes-cli
  - krr
  - kustomize
  - krew
  - magic-wormhole
  - pre-commit
  - restic
  - sops
  - sqlite
  - talhelper
  - fisher
  - llm
  - uv
  - volta

uv_tools:
  - --python python3.12 aider-chat@latest

winget_packages:
  - eza-community.eza
  - Starship.Starship
  - Fork.Fork
  - Git.Git
  - Microsoft.VisualStudioCode
  - Microsoft.WindowsTerminal
  - Microsoft.PowerToys
  - SlackTechnologies.Slack
  - Microsoft.AzureCLI
  - Microsoft.Azure.StorageExplorer
  - astral-sh.uv
  - AgileBits.1Password.CLI
  - 9NKSQGP7F2NH # WhatsApp
  - Obsidian.Obsidian
  - Mirantis.Lens
  - FluxCD.Flux
  - Discord.Discord
  - Kubernetes.kubectl
  - Anysphere.Cursor
  - Volta.Volta

kubectl_krew_plugins:
  - explore

fisher_plugins:
  - jorgebucaran/fisher
  - jorgebucaran/nvm.fish
  - z11i/github-copilot-cli.fish

kubeconfig_onepassword_sources:
  - path: op://Homelab/Kubeconfig/notesPlain
  - path: op://K8s - akl-flux-cluster/kubeconfig/notesPlain
  # Add more as needed