format = """
[](color_orange)\
$os\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$nodejs\
$python\
[](fg:color_blue bg:color_bg3)\
$docker_context\
[](fg:color_bg3 bg:color_bg1)\
$time\
[](fg:color_bg1)\
$status\
$line_break\
$character\
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
color_text = '#ffffff'

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[$user ]($style)'
disabled = false

[hostname]
ssh_only = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:color_orange fg:color_fg0"
disabled = false # Disabled by default

[os.symbols]
Windows = " "
Ubuntu = "󰕈 "

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
use_os_path_sep = false
truncation_length = 2
truncate_to_repo = true
fish_style_pwd_dir_length = 1


[character]
format = '$symbol '
success_symbol = '[❯](bold fg:color_green)[❯](bold fg:color_aqua)'
error_symbol = '[❯❯](bold fg:color_red)'

[docker_context]
symbol = " "
style = "fg:color_text bg:color_bg3"
format = '[ $symbol $context ]($style)'


[git_branch]
symbol = ""
style = "fg:color_text bg:color_aqua"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:color_text bg:color_aqua"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "fg:color_text bg:color_blue"
format = '[ $symbol ($version) ]($style)'
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[python]
symbol = ""
style = "fg:color_text bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[status]
disabled = false
symbol = '❌'
success_symbol = ''
not_executable_symbol = '🚫'
not_found_symbol = '🔍'
sigint_symbol = '🧱'
signal_symbol = '⚡'
style = 'bold red'
format = ' [\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
recognize_signal_code = true
map_symbol = true
